[package]
name = "encryption"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packet = { path = "../packet" }
error = { path = "../error" }
rsa = "0.5"
ring = "0.16.20"