
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_fmt:
    name: Check cargo formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  build-linux:
    name: Build check on linux & wasm32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Linux
        run: cargo build
      - name: Build Wasm32
        run: rustup target add wasm32-unknown-unknown && cargo build --target wasm32-unknown-unknown
      - name: Test
        run: cargo test
      - name: Doc test
        run: cargo test --doc

  build-windows:
    name: Build check on windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Build Windows
        run: cargo build
